Repository AY2122S1-CS2103-W14-2/tp, pull requests merged in 2021-11, with the labels that each got.

#206 Fix Gui Display Issue
  docs/images/Ui.png
  src/main/java/seedu/track2gather/ui/PersonCard.java
Labels: priority.High

#229 Fix User Guide to clarify Find command
  docs/UserGuide.md
Labels: type.Bug, priority.High

#228 Fix bug in TShift command
  src/main/java/seedu/track2gather/logic/commands/TShiftCommand.java
Labels: type.Bug, priority.High, severity.High

#230 Fix Markdown HTML
  docs/UserGuide.md
Labels: type.Bug

#218 Update Developer's Guide for v1.4
  docs/DeveloperGuide.md
  docs/diagrams/ModelClassDiagram.puml
Labels: type.Task, priority.High

#221 Update user-visible messages (command results) to address PE-D bugs
  src/main/java/seedu/track2gather/commons/core/Messages.java
  src/main/java/seedu/track2gather/logic/commands/AddCommand.java
  src/main/java/seedu/track2gather/logic/commands/DeleteCommand.java
  src/main/java/seedu/track2gather/logic/commands/EditCommand.java
  src/main/java/seedu/track2gather/logic/commands/FCallCommand.java
  src/main/java/seedu/track2gather/logic/commands/FindCommand.java
  src/main/java/seedu/track2gather/logic/commands/ListCommand.java
  src/main/java/seedu/track2gather/logic/commands/SCallCommand.java
  src/main/java/seedu/track2gather/logic/commands/ScheduleCommand.java
  src/main/java/seedu/track2gather/logic/commands/SessionCommand.java
  src/main/java/seedu/track2gather/logic/commands/SortCommand.java
  src/main/java/seedu/track2gather/logic/commands/TShiftCommand.java
  src/main/java/seedu/track2gather/model/person/Person.java
  src/main/java/seedu/track2gather/storage/JsonSerializableTrack2Gather.java
  src/test/java/seedu/track2gather/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/track2gather/logic/commands/FindCommandTest.java
  src/test/java/seedu/track2gather/logic/commands/SortCommandTest.java
  src/test/java/seedu/track2gather/logic/commands/TShiftCommandTest.java
Labels: type.Bug, priority.High, severity.Medium

#233 Fix typo in UG
  docs/UserGuide.md
Labels: type.Bug, priority.High, severity.Low

#225 Add tests for enforcement
  src/test/java/seedu/track2gather/logic/commands/FCallCommandTest.java
  src/test/java/seedu/track2gather/logic/commands/FindCommandTest.java
  src/test/java/seedu/track2gather/logic/commands/SCallCommandTest.java
  src/test/java/seedu/track2gather/logic/commands/ScheduleCommandTest.java
  src/test/java/seedu/track2gather/logic/commands/SessionCommandTest.java
  src/test/java/seedu/track2gather/logic/parser/FCallCommandParserTest.java
  src/test/java/seedu/track2gather/logic/parser/SCallCommandParserTest.java
  src/test/java/seedu/track2gather/logic/parser/Track2GatherParserTest.java
Labels: priority.High

#236 Update Jennifer's PPP (v1.4)
  docs/team/jennibearduit.md
Labels: type.Task, priority.High

#242 Edit Period class help message
  src/main/java/seedu/track2gather/model/person/attributes/Period.java
Labels: priority.Medium, severity.Medium

#249 EditCommandParser remove redundant checks
  src/main/java/seedu/track2gather/logic/parser/EditCommandParser.java
Labels: priority.Medium, severity.Medium

#250 Fixed command bugs.
  src/main/java/seedu/track2gather/commons/core/index/Index.java
  src/main/java/seedu/track2gather/logic/commands/DeleteCommand.java
  src/main/java/seedu/track2gather/logic/commands/EditCommand.java
  src/main/java/seedu/track2gather/logic/commands/FCallCommand.java
  src/main/java/seedu/track2gather/logic/commands/SCallCommand.java
  src/main/java/seedu/track2gather/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/track2gather/model/person/Person.java
  src/test/java/seedu/track2gather/logic/commands/EditCommandTest.java
  src/test/java/seedu/track2gather/logic/commands/FCallCommandTest.java
  src/test/java/seedu/track2gather/logic/commands/SCallCommandTest.java
  src/test/java/seedu/track2gather/logic/parser/DeleteCommandParserTest.java
Labels: type.Bug, severity.High

#251 Add assert statements to improve defensiveness in editcommandparser
  src/main/java/seedu/track2gather/logic/parser/EditCommandParser.java
Labels: priority.Medium

#222 Prepare PPP for Lauren
  docs/AboutUs.md
  docs/team/lrnshk.md
Labels: type.Task, priority.High

#255 Fix bug in link to the UG
  docs/DeveloperGuide.md
Labels: type.Bug, priority.High, severity.Medium

#259 Bugfix: next of kin particulars not aligned
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListCard.fxml
Labels: type.Bug, priority.Medium, severity.Medium

#264 Delete command: Fix to ignore whitespaces surrounding or between indices
  src/main/java/seedu/track2gather/logic/parser/ParserUtil.java
Labels: type.Bug, priority.High, severity.Medium

#262 Clear command: Fix to clear all instead of displayed persons
  docs/UserGuide.md
  src/main/java/seedu/track2gather/logic/commands/ClearCommand.java
Labels: type.Bug, priority.High, severity.High

#266 CaseNumber: Standardise help messages
  docs/UserGuide.md
  src/main/java/seedu/track2gather/model/person/attributes/CaseNumber.java
Labels: type.Task, priority.Low, severity.VeryLow

#260 SortCommand: Sort contacts without SHN periods below
  src/main/java/seedu/track2gather/logic/commands/SortCommand.java
  src/test/java/seedu/track2gather/logic/commands/SortCommandTest.java
Labels: type.Bug, priority.High, severity.Medium

#263 UG: Amend Find command table to explain in terms of keywords
  docs/UserGuide.md
Labels: type.Task, priority.Medium, severity.Low

#257 Impose stricter validation for phone numbers
  docs/UserGuide.md
  src/main/java/seedu/track2gather/model/person/attributes/Phone.java
  src/test/java/seedu/track2gather/model/person/PhoneTest.java
Labels: type.Enhancement, priority.Medium

#237 Update README.md
  README.md
  docs/index.md
  src/main/resources/images/track2gather_32.png
Labels: type.Task, priority.Medium

#269 Fix README.md links to webpages
  docs/index.md
Labels: priority.Medium

#268 Fix EditCommand Result, UG and DG bugs
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/track2gather/logic/commands/EditCommand.java
  src/main/java/seedu/track2gather/model/person/attributes/Name.java
Labels: type.Bug, severity.Medium

#270 Fix README.md and index.md links
  README.md
  docs/index.md
Labels: priority.Medium

#254 Prepare PPP for @frederickpek
  docs/team/frederickpek.md
Labels: type.Task

#275 Update Ui.png
  docs/images/Ui.png
Labels: priority.High

#272 DG: Standardise alignment of lists in Use Cases
  docs/DeveloperGuide.md
Labels: type.Bug, severity.VeryLow

#271 Fix minor UG/DG bugs
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/ModelClassDiagram.png
Labels: type.Bug, severity.Medium

#276 Fix HTML in the UG
  docs/UserGuide.md
Labels: type.Bug, priority.High, severity.Medium

#273 Update PPP for @frederickpek
  docs/team/frederickpek.md
Labels: priority.Medium

#277 Update PPP for @frederickpek
  docs/team/frederickpek.md
Labels: priority.Medium

#282 Add tshift equality checks to Track2GatherParserTest
  src/test/java/seedu/track2gather/logic/parser/Track2GatherParserTest.java
Labels: priority.High

#278 DG: Fix assorted issues
  docs/DeveloperGuide.md
  docs/diagrams/UndoRedoState0.puml
  docs/diagrams/UndoRedoState1.puml
  docs/diagrams/UndoRedoState2.puml
  docs/diagrams/UndoRedoState3.puml
  docs/diagrams/UndoRedoState4.puml
  docs/diagrams/UndoRedoState5.puml
  docs/diagrams/UndoSequenceDiagram.puml
  docs/images/ArchitectureDiagram.png
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/CommitActivityDiagram.png
  docs/images/ComponentManagers.png
  docs/images/DeleteSequenceDiagram.png
  docs/images/LogicClassDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/ParserClasses.png
  docs/images/StorageClassDiagram.png
  docs/images/UiClassDiagram.png
  docs/images/UndoRedoState0.png
  docs/images/UndoRedoState1.png
  docs/images/UndoRedoState2.png
  docs/images/UndoRedoState3.png
  docs/images/UndoRedoState4.png
  docs/images/UndoRedoState5.png
  docs/images/UndoSequenceDiagram.png
Labels: type.Task, priority.High

#284 Minor modifications to various commands and parsers
  src/main/java/seedu/track2gather/logic/commands/ClearCommand.java
  src/main/java/seedu/track2gather/logic/commands/DeleteCommand.java
  src/main/java/seedu/track2gather/logic/commands/SCallCommand.java
  src/main/java/seedu/track2gather/logic/commands/SortCommand.java
  src/main/java/seedu/track2gather/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/track2gather/logic/parser/FindCommandParser.java
Labels: type.Enhancement

#286 Add Lutfi's PPP
  docs/team/luffingluffy.md
Labels: type.Task

#280 Add PPP for @wei2912
  docs/team/wei2912.md
Labels: type.Task, priority.High

#285 Fix Javadocs to be consistent with UG/DG
  src/main/java/seedu/track2gather/logic/commands/AddCommand.java
  src/main/java/seedu/track2gather/logic/commands/ClearCommand.java
  src/main/java/seedu/track2gather/logic/commands/DeleteCommand.java
  src/main/java/seedu/track2gather/logic/commands/EditCommand.java
  src/main/java/seedu/track2gather/logic/commands/ExitCommand.java
  src/main/java/seedu/track2gather/logic/commands/FCallCommand.java
  src/main/java/seedu/track2gather/logic/commands/FindCommand.java
  src/main/java/seedu/track2gather/logic/commands/HelpCommand.java
  src/main/java/seedu/track2gather/logic/commands/ListCommand.java
  src/main/java/seedu/track2gather/logic/commands/SCallCommand.java
  src/main/java/seedu/track2gather/logic/commands/ScheduleCommand.java
  src/main/java/seedu/track2gather/logic/commands/SessionCommand.java
  src/main/java/seedu/track2gather/logic/commands/SortCommand.java
  src/main/java/seedu/track2gather/logic/commands/TShiftCommand.java
Labels: type.Task

#287 Add Lutfi's PPP.
  docs/team/luffingluffy.md
Labels: type.Task

#289 Hotfix: gui case number getting cut on windows
  src/main/resources/view/MainWindow.fxml
Labels: priority.High
