Repository AY2122S1-CS2103-W14-2/tp, pull requests merged in 2021-09, with the labels that each got.

#5 Update README.md
  README.md
  docs/images/Ui.png
Labels: documentation

#13 Add Frederick's information to AboutUs.md
  docs/AboutUs.md
  docs/images/frederickpek.png
  docs/team/frederickpek.md
Labels: documentation

#14 Add Andrew's information to docs
  docs/AboutUs.md
  docs/images/andrew.png
  docs/team/andrew.md
Labels: documentation

#18 Add CODEOWNERS
  CODEOWNERS
Labels: enhancement

#20 Add Jennifer to AboutUs.md
  docs/AboutUs.md
  docs/images/jennibearduit.png
  docs/team/jennibearduit.md
Labels: documentation

#21 Add Wei En to AboutUs.md
  docs/AboutUs.md
  docs/images/wei2912.png
  docs/team/wei2912.md
Labels: documentation

#24 Fix Andrew's aboutUs documentation files naming
  docs/AboutUs.md
  docs/images/over-fitted.png
  docs/team/over-fitted.md
Labels: documentation

#15 Update DeveloperGuide.md
  docs/DeveloperGuide.md
Labels: documentation

#22 Update Jekyll site settings
  docs/_config.yml
  docs/_sass/minima/_base.scss
Labels: documentation

#26 Gui v1
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/images/email_icon.png
  src/main/resources/images/home_icon.png
  src/main/resources/images/phone_icon.png
  src/main/resources/images/track2gather_icon.png
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListCard.fxml
Labels: enhancement

#23 Update UserGuide.md for Track2Gather
  docs/UserGuide.md
Labels: documentation, admin

#32 Update index.md for Track2Gather
  docs/index.md
Labels: documentation, enhancement

#33 Remove all instances of AB3 from UserGuide.md
  docs/UserGuide.md
  docs/images/findAlexDavidResult.png
  docs/images/helpMessage.png
Labels: documentation, enhancement
